In [ ]:
import sys
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("hello world")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

hello world
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [ ]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [ ]:
name = "Alice"
greeting = "Hello, World!"
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


In [ ]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [ ]:
num = 10
if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Non-positive")

Positive


In [ ]:
x = 5
y = 10
if x > 0 and y < 20:
    print("Both conditions are true")
if x > 0 or y > 20:
    print("At least one condition is true")
if not x == 0:
    print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_length(value, from_unit, to_unit):
    """
    Convert length between meters and feet.

    Parameters:
    value (float): The value to be converted.
    from_unit (str): The unit of the input value ('m' or 'ft').
    to_unit (str): The unit to convert to ('m' or 'ft').

    Returns:
    float: The converted value.

    Raises:
    ValueError: If the input units are not supported.
    """
    if from_unit == 'm' and to_unit == 'ft':
        return value * 3.28084
    elif from_unit == 'ft' and to_unit == 'm':
        return value / 3.28084
    else:
        raise ValueError("Unsupported conversion type. Please use 'm' or 'ft'.")
def convert_weight(value, from_unit, to_unit):
    """
    Convert weight between kilograms and pounds.

    Parameters:
    value (float): The value to be converted.
    from_unit (str): The unit of the input value ('kg' or 'lbs').
    to_unit (str): The unit to convert to ('kg' or 'lbs').

    Returns:
    float: The converted value.

    Raises:
    ValueError: If the input units are not supported.
    """
    if from_unit == 'kg' and to_unit == 'lbs':
        return value * 2.20462
    elif from_unit == 'lbs' and to_unit == 'kg':
        return value / 2.20462
    else:
        raise ValueError("Unsupported conversion type. Please use 'kg' or 'lbs'.")

def convert_volume(value, from_unit, to_unit):
    """
    Convert volume between liters and gallons.

    Parameters:
    value (float): The value to be converted.
    from_unit (str): The unit of the input value ('L' or 'gal').
    to_unit (str): The unit to convert to ('L' or 'gal').

    Returns:
    float: The converted value.

    Raises:
    ValueError: If the input units are not supported.
    """
    if from_unit == 'L' and to_unit == 'gal':
        return value * 0.264172
    elif from_unit == 'gal' and to_unit == 'L':
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type. Please use 'L' or 'gal'.")
def main():
    print("Welcome to the Unit Converter!")
    print("Choose the type of conversion:")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")

    choice = input("Enter your choice (1/2/3): ")

    try:
        if choice == '1':
            value = float(input("Enter the value to convert: "))
            from_unit = input("Convert from (m/ft): ")
            to_unit = input("Convert to (m/ft): ")
            result = convert_length(value, from_unit, to_unit)
            print(f"Converted value: {result:.2f} {to_unit}")
        elif choice == '2':
            value = float(input("Enter the value to convert: "))
            from_unit = input("Convert from (kg/lbs): ")
            to_unit = input("Convert to (kg/lbs): ")
            result = convert_weight(value, from_unit, to_unit)
            print(f"Converted value: {result:.2f} {to_unit}")
        elif choice == '3':
            value = float(input("Enter the value to convert: "))
            from_unit = input("Convert from (L/gal): ")
            to_unit = input("Convert to (L/gal): ")
            result = convert_volume(value, from_unit, to_unit)
            print(f"Converted value: {result:.2f} {to_unit}")
        else:
            print("Invalid choice. Please select 1, 2, or 3.")
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()

Welcome to the Unit Converter!
Choose the type of conversion:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Enter your choice (1/2/3): 1
Enter the value to convert: 56
Convert from (m/ft): m
Convert to (m/ft): ft
Converted value: 183.73 ft


Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers in the list.
    """
    return sum(numbers)
def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers in the list.
    """
    if not numbers:
        raise ValueError("The list of numbers is empty.")
    return sum(numbers) / len(numbers)
def calculate_maximum(numbers):
    """
    Calculate the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum value in the list.
    """
    if not numbers:
        raise ValueError("The list of numbers is empty.")
    return max(numbers)

def calculate_minimum(numbers):
    """
    Calculate the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum value in the list.
    """
    if not numbers:
        raise ValueError("The list of numbers is empty.")
    return min(numbers)
def main():
    print("Welcome to the Mathematical Operations Program!")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1/2/3/4): ")

    try:
        numbers_input = input("Enter a list of numbers (separated by spaces): ")
        numbers = [float(num) for num in numbers_input.split()]

        if choice == '1':
            result = calculate_sum(numbers)
            print(f"The sum of the numbers is: {result}")
        elif choice == '2':
            result = calculate_average(numbers)
            print(f"The average of the numbers is: {result}")
        elif choice == '3':
            result = calculate_maximum(numbers)
            print(f"The maximum value is: {result}")
        elif choice == '4':
            result = calculate_minimum(numbers)
            print(f"The minimum value is: {result}")
        else:
            print("Invalid choice. Please select 1, 2, 3, or 4.")
    except ValueError as e:
        print(f"Error: {e}")

main()

Welcome to the Mathematical Operations Program!
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 1
Enter a list of numbers (separated by spaces): 5 6 4
The sum of the numbers is: 15.0


1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Extract every other element from a list, starting from the first element.

    Parameters:
    lst (list): The input list from which to extract elements.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]
def main():
    input_list = input("Enter a list of elements (separated by spaces): ")
    lst = input_list.split()
    result = extract_every_other(lst)
    print(f"Every other element: {result}")
if __name__ == "__main__":
    main()

Enter a list of elements (separated by spaces): 1 2 5 6 4 
Every other element: ['1', '5', '4']


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:


def get_sublist(lst, start, end):
    """
    Return a sublist from a given list, starting from a specified index and ending at another specified index.

    Parameters:
    lst (list): The input list from which to extract the sublist.
    start (int): The starting index of the sublist (inclusive).
    end (int): The ending index of the sublist (inclusive).

    Returns:
    list: A sublist from start to end (inclusive).

    Raises:
    ValueError: If start or end indices are out of range.
    """
    if start < 0 or end >= len(lst) or start > end:
        raise ValueError("Invalid start or end index.")
    return lst[start:end + 1]
def main():
    input_list = input("Enter a list of elements (separated by spaces): ")
    lst = input_list.split()
    start = int(input("Enter the starting index: "))
    end = int(input("Enter the ending index: "))

    try:
        result = get_sublist(lst, start, end)
        print(f"Sublist from index {start} to {end}: {result}")
    except ValueError as e:
        print(f"Error: {e}")
if __name__ == "__main__":
    main()

Enter a list of elements (separated by spaces): 4 5 6 5 4 
Enter the starting index: 4
Enter the ending index: 4
Sublist from index 4 to 4: ['4']


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
    lst (list): The input list to be reversed.

    Returns:
    list: A new list that is the reverse of the input list.
    """
    return lst[::-1]
def main():
    input_list = input("Enter a list of elements (separated by spaces): ")
    lst = input_list.split()
    result = reverse_list(lst)
    print(f"Reversed list: {result}")
if __name__ == "__main__":
    main()

Enter a list of elements (separated by spaces): 1 2 3 4 5
Reversed list: ['5', '4', '3', '2', '1']


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:

def remove_first_last(lst):
    """
    Remove the first and last elements of a list and return the resulting sublist.

    Parameters:
    lst (list): The input list from which to remove the first and last elements.

    Returns:
    list: A new list without the first and last elements of the original list.

    Raises:
    ValueError: If the input list has less than 3 elements.
    """
    if len(lst) < 3:
        raise ValueError("The list must have at least 3 elements to remove the first and last.")
    return lst[1:-1]
def main():
    input_list = input("Enter a list of elements (separated by spaces): ")
    lst = input_list.split()

    try:
        result = remove_first_last(lst)
        print(f"List after removing first and last elements: {result}")
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()

Enter a list of elements (separated by spaces): 1 2 5 4 6 3
List after removing first and last elements: ['2', '5', '4', '6']


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """
    Extract the last n elements of a list using slicing.

    Parameters:
    lst (list): The input list from which to extract elements.
    n (int): The number of elements to extract from the end of the list.

    Returns:
    list: A new list containing the last n elements of the original list.
    """
    return lst[-n:]
def main():
    input_list = input("Enter a list of elements (separated by spaces): ")
    lst = input_list.split()
    n = int(input("Enter the number of elements to extract from the end: "))

    result = get_last_n(lst, n)
    print(f"The last {n} elements: {result}")
if __name__ == "__main__":
    main()

Enter a list of elements (separated by spaces): 1 5 4 6 2 3
Enter the number of elements to extract from the end: 6
The last 6 elements: ['1', '5', '4', '6', '2', '3']


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:

def reverse_skip(lst):
    """
    Extract a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

    Parameters:
    lst (list): The input list from which to extract elements.

    Returns:
    list: A new list containing every second element starting from the second-to-last, moving backward.
    """
    return lst[-2::-2]
def main():
    input_list = input("Enter a list of elements (separated by spaces): ")
    lst = input_list.split()

    result = reverse_skip(lst)
    print(f"Elements in reverse order with skip: {result}")
if __name__ == "__main__":
    main()

Enter a list of elements (separated by spaces): 4 5 6 8 5 2 1
Elements in reverse order with skip: ['2', '8', '5']


4.3 Exercise on Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """
    Flatten a nested list into a single list.

    Parameters:
    lst (list): The input nested list to be flattened.

    Returns:
    list: A new list that is a flattened version of the input list.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list
def main():
    input_list = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")
    nested_list = eval(input_list)
    result = flatten(nested_list)
    print(f"Flattened list: {result}")
if __name__ == "__main__":
    main()

Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): [[1, 5], [5, 8], [4, 9]]
Flattened list: [1, 5, 5, 8, 4, 9]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """
    Extract a specific element from a nested list given its indices.

    Parameters:
    lst (list): The input nested list.
    indices (list): A list of indices that specify the position of the element to extract.

    Returns:
    The element at the specified position in the nested list.

    Raises:
    ValueError: If the indices are out of range or if the structure of the nested list does not match the indices.
    """
    try:
        element = lst
        for index in indices:
            element = element[index]
        return element
    except (IndexError, TypeError) as e:
        raise ValueError("Invalid indices or nested list structure.") from e
def main():
    input_list = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")
    nested_list = eval(input_list)
    indices_input = input("Enter the indices to access (separated by spaces): ")
    indices = [int(i) for i in indices_input.split()]
    try:
        result = access_nested_element(nested_list, indices)
        print(f"The element at the specified indices is: {result}")
    except ValueError as e:
        print(f"Error: {e}")
if __name__ == "__main__":
    main()

Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): [[1, 2], [3, 4], [5, 8], [9, 1]]
Enter the indices to access (separated by spaces): 1
The element at the specified indices is: [3, 4]


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """
    Calculate the sum of all the numbers in a nested list (regardless of depth).

    Parameters:
    lst (list): The input nested list containing numbers.

    Returns:
    float: The sum of all the numbers in the nested list.
    """
    total_sum = 0
    for item in lst:
        if isinstance(item, list):
            total_sum += sum_nested(item)
        else:
            total_sum += item
    return total_sum
def main():
    input_list = input("Enter a nested list of numbers (e.g., [[1, 2], [3, [4, 5]], 6]): ")
    nested_list = eval(input_list)
    result = sum_nested(nested_list)
    print(f"The sum of all elements in the nested list is: {result}")
if __name__ == "__main__":
    main()


Enter a nested list of numbers (e.g., [[1, 2], [3, [4, 5]], 6]): [[1, 2], [3, [4, 5]], 6]
The sum of all elements in the nested list is: 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:

def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The input nested list from which to remove the element.
    elem: The element to be removed from the nested list.

    Returns:
    list: A new nested list with the specified element removed.
    """
    if isinstance(lst, list):
        return [remove_element(item, elem) for item in lst if item != elem]
    else:
        return lst
def main():
    input_list = input("Enter a nested list (e.g., [[1, 2], [3, 2], [4, 5]]): ")
    nested_list = eval(input_list)
    elem = input("Enter the element to remove: ")
    result = remove_element(nested_list, elem)
    print(f"Nested list after removing element '{elem}': {result}")
if __name__ == "__main__":
    main()

Enter a nested list (e.g., [[1, 2], [3, 2], [4, 5]]): [[1, 2], [3, 6], [4, 5], [8, 6]]
Enter the element to remove: 1
Nested list after removing element '1': [[1, 2], [3, 6], [4, 5], [8, 6]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """
    Find the maximum element in a nested list (regardless of depth).

    Parameters:
    lst (list): The input nested list containing numbers.

    Returns:
    float: The maximum element in the nested list.
    """
    max_element = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_element = max(max_element, find_max(item))
        else:
            max_element = max(max_element, item)
    return max_element
def main():
    input_list = input("Enter a nested list of numbers (e.g., [[1, 2], [3, [4, 5]], 6]): ")
    nested_list = eval(input_list)
    result = find_max(nested_list)
    print(f"The maximum element in the nested list is: {result}")
if __name__ == "__main__":
    main()

Enter a nested list of numbers (e.g., [[1, 2], [3, [4, 5]], 6]): [[1, 2], [3, [4, 5]], 6]
The maximum element in the nested list is: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:

def count_occurrences(lst, elem):
    """
    Count how many times a specific element appears in a nested list.

    Parameters:
    lst (list): The input nested list.
    elem: The element to count in the nested list.

    Returns:
    int: The count of occurrences of the specified element in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count
def main():
    input_list = input("Enter a nested list (e.g., [[1, 2], [2, 3], [2, 4]]): ")
    nested_list = eval(input_list)
    elem = input("Enter the element to count: ")
    result = count_occurrences(nested_list, elem)
    print(f"The element '{elem}' appears {result} times in the nested list.")
if __name__ == "__main__":
    main()

Enter a nested list (e.g., [[1, 2], [2, 3], [2, 4]]): [[1, 2], [2, 3], [2, 4]]
Enter the element to count: 2
The element '2' appears 0 times in the nested list.


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single list, regardless of the depth.

    Parameters:
    lst (list): The input deeply nested list to be flattened.

    Returns:
    list: A new list that is a flattened version of the input list.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list
def main():
    input_list = input("Enter a deeply nested list (e.g., [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]): ")
    nested_list = eval(input_list)
    result = deep_flatten(nested_list)
    print(f"Flattened list: {result}")
if __name__ == "__main__":
    main()

Enter a deeply nested list (e.g., [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]): [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:

def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.

    Parameters:
    lst (list): The input nested list containing numbers.

    Returns:
    float: The average of all the elements in the nested list.

    Raises:
    ValueError: If the nested list is empty or contains non-numeric values.
    """
    flat_list = deep_flatten(lst)
    if not flat_list:
        raise ValueError("The nested list is empty.")
    return sum(flat_list) / len(flat_list)
def main():
    input_list = input("Enter a nested list of numbers (e.g., [[1, 2], [3, 4], [5, 6]]): ")
    nested_list = eval(input_list)
    try:
        result = average_nested(nested_list)
        print(f"The average of all elements in the nested list is: {result}")
    except ValueError as e:
        print(f"Error: {e}")
if __name__ == "__main__":
    main()

Enter a nested list of numbers (e.g., [[1, 2], [3, 4], [5, 6]]): [[1, 2], [3, 4], [5, 6]]
The average of all elements in the nested list is: 3.5


10 To - Do - NumPy
Please complete all the problems listed below:

10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print("Empty Array (2x2):")
print(empty_array)
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):")
print(ones_array)
shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value)
print("\nFilled Array (3x3) with value 7:")
print(filled_array)
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Like Given Array:")
print(zeros_like_array)
ones_like_array = np.ones_like(given_array)
print("\nOnes Like Given Array:")
print(ones_like_array)
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumpy Array from List:")
print(numpy_array)




Empty Array (2x2):
[[4.73249117e-315 0.00000000e+000]
 [5.78689210e-317 6.72244982e-310]]

All Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array (3x3) with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Given Array:
[[0 0]
 [0 0]]

Ones Like Given Array:
[[1 1]
 [1 1]]

Numpy Array from List:
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array with values from 10 to 49:")
print(array_10_to_49)

# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:")
print(matrix_3x3)

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:")
print(random_array)
print("Mean of the random array:", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Array with random values:")
print(random_10x10)
print("Minimum value in the 10x10 array:", min_value)
print("Maximum value in the 10x10 array:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Replace the 5th element (index 4) with 1
print("\nZero array of size 10 with 5th element replaced by 1:")
print(zero_array)

# 7. Reverse an array arr = [1, 2, 0,0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nOriginal array:", arr)
print("Reversed array:", reversed_arr)

# 8. Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:")
print(border_array)

# 9. Create a 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill odd rows with 1s
checkerboard[::2, 1::2] = 1  # Fill even rows with 1s
print("\n8x8 Checkerboard pattern:")
print(checkerboard)


Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
[0.42935615 0.06495078 0.45905212 0.0625085  0.04924798 0.62283141
 0.98765776 0.08332099 0.83873263 0.20306915 0.03864041 0.86118187
 0.66332587 0.43802047 0.78905995 0.59606895 0.43551649 0.62700553
 0.57296836 0.87902663 0.71357889 0.44383813 0.89912371 0.89317873
 0.02189198 0.89462826 0.90130191 0.00359503 0.64130447 0.43343148]
Mean of the random array: 0.5182471530550354

10x10 Array with random values:
[[0.5761339  0.09451503 0.1584673  0.25836166 0.463683   0.66577946
  0.81577401 0.15592684 0.88536547 0.05353875]
 [0.30455513 0.81888934 0.10052574 0.87119524 0.72613663 0.76324243
  0.64505112 0.33768592 0.74528871 0.34409312]
 [0.80641422 0.39521735 0.09951383 0.7914564  0.00

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:")
print(add_xy)

# 2. Subtract the two arrays
subtract_xy = x - y
print("\nSubtraction of x and y:")
print(subtract_xy)

# 3. Multiply the array with any integers of your choice
mult_x = x * 3  # Multiplying x by 3
print("\nMultiplication of x by 3:")
print(mult_x)

# 4. Find the square of each element of the array
square_x = x ** 2
print("\nSquare of each element in x:")
print(square_x)

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y
dot_vw = np.dot(v, w)
print("\nDot product of v and w:")
print(dot_vw)
dot_xv = np.dot(x, v)
print("\nDot product of x and v:")
print(dot_xv)
dot_xy = np.dot(x, y)
print("\nDot product of x and y:")
print(dot_xy)

# 6. Concatenate x(and)y along row and Concatenate v(and)w along column
concat_xy_row = np.concatenate((x, y), axis=0)  # Concatenate along rows
print("\nConcatenation of x and y along rows:")
print(concat_xy_row)
concat_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # Concatenate along columns
print("\nConcatenation of v and w along columns:")
print(concat_vw_col)

# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:")
    print(concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:")
    print(e)
    print("Explanation: The error occurs because x is a 2D array with shape (2, 2) and v is a 1D array with shape (2,). They cannot be concatenated along the specified axis due to their different dimensions.")


Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplication of x by 3:
[[ 3  6]
 [ 9 15]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
[[ 9 11]
 [10 12]]

Error while concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The error occurs because x is a 2D array with shape (2, 2) and v is a 1D array with shape (2,). They cannot be concatenated along the specified axis due to their different dimensions.


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A multiplied by its inverse (A.A^-1):")
print(identity_matrix)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:")
print(AB)
print("\nBA:")
print(BA)
print("\nIs AB equal to BA?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_transpose = AB.T
B_transpose = B.T
A_transpose = A.T
BA_transpose = np.dot(B_transpose, A_transpose)
print("\n(AB)^T:")
print(AB_transpose)
print("\nB^T A^T:")
print(BA_transpose)
print("\nIs (AB)^T equal to B^T A^T?", np.array_equal(AB_transpose, BA_transpose))
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("\nSolution to the system of linear equations (X):")
print(X)

A multiplied by its inverse (A.A^-1):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

Is AB equal to BA? False

(AB)^T:
[[23 51]
 [13 29]]

B^T A^T:
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T? True

Solution to the system of linear equations (X):
[ 2.  1. -2.]
